name: syngenie
favicon: null
layout_spectrum: 0.9155136961489916
typography_spectrum: 0.42515246220864356
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8454552795737982
  lightness: 0.9117348152212799
  saturation: 0.23974382667802274
  rhythmicContrast: 0.8557677092030644
purpose: []
